name: Python 应用程序

on:
  workflow_dispatch:
    inputs:
      app_id:
        description: '传递给脚本的 AppID'
        required: true
        default: '0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 检出代码库
      uses: actions/checkout@v2

    - name: 设置 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 安装依赖项
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 运行主脚本
      env:
        APP_ID: ${{ github.event.inputs.app_id }}
      run: |
        python main.py
